In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../00-data/course_lead_scoring_2026.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               4852 non-null   str
 1   industry                  4760 non-null   str
 2   employment_status         4806 non-null   str
 3   location                  4792 non-null   str
 4   annual_income             4631 non-null   float64
 5   number_of_courses_viewed  5000 non-null   int64
 6   interaction_count         5000 non-null   int64
 7   lead_score                4965 non-null   float64
 8   converted                 5000 non-null   int64
dtypes: float64(2), int64(3), str(4)
memory usage: 351.7 KB

In [5]:
df.describe()

,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
count,4631.000000,5000.000000,5000.000000,4965.000000,5000.000000
mean,54533.212049,2.089400,4.472600,0.494767,0.576600
std,21245.661710,1.188987,2.435906,0.199431,0.494147
min,12000.000000,0.000000,0.000000,0.010000,0.000000
25%,40458.500000,1.000000,3.000000,0.360000,0.000000
50%,55051.000000,2.000000,4.000000,0.490000,1.000000
75%,71252.500000,3.000000,6.000000,0.630000,1.000000
max,109886.000000,6.000000,13.000000,0.990000,1.000000

In [6]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [7]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [10]:
categorical_columns = df.select_dtypes(include=['object']).columns
numerical_columns = df.select_dtypes(include=['number']).columns

C:\Users\khalid\AppData\Local\Temp\ipykernel_24564\321798312.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

In [11]:
print(categorical_columns)
print(numerical_columns)

Index(['lead_source', 'industry', 'employment_status', 'location'], dtype='str')
Index(['annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [13]:
for ccol in categorical_columns:
    df[ccol] = df[ccol].fillna('NA')
for ncol in numerical_columns:
    df[ncol] = df[ncol].fillna(0.0)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               5000 non-null   str
 1   industry                  5000 non-null   str
 2   employment_status         5000 non-null   str
 3   location                  5000 non-null   str
 4   annual_income             5000 non-null   float64
 5   number_of_courses_viewed  5000 non-null   int64
 6   interaction_count         5000 non-null   int64
 7   lead_score                5000 non-null   float64
 8   converted                 5000 non-null   int64
dtypes: float64(2), int64(3), str(4)
memory usage: 351.7 KB

In [18]:

from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_valid = train_test_split(df_full_train, test_size=0.25, random_state=1)

#### Question 1: ROC AUC feature importance

In [24]:
from sklearn.metrics import roc_auc_score
auc_scores = {}

for feature in numerical_columns:
    if feature == 'converted':continue
    auc = roc_auc_score(df_train['converted'], df_train[feature])
    auc_scores[feature] = max(auc, 1 - auc)

print(auc_scores)

best_feature = max(auc_scores, key=auc_scores.get)
print("Answer:", best_feature)

{'annual_income': 0.6081977776250831, 'number_of_courses_viewed': 0.7229894623989618, 'interaction_count': 0.7649203047563227, 'lead_score': 0.7882254810906102}
Answer: lead_score

#### Question 2: Training the model

In [29]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

dv = DictVectorizer(sparse=False)
y_train = df_train['converted']
y_valid = df_valid['converted']

X_train = df_train.drop(columns=['converted'])
X_valid = df_valid.drop(columns=['converted'])


train_dicts = X_train.to_dict(orient='records')
valid_dicts = X_valid.to_dict(orient='records')


X_train_encoded = dv.fit_transform(train_dicts)
X_valid_encoded = dv.transform(valid_dicts)

In [ ]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000)

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0.])